### ISSUE TITLE
Getting a 403 on a push?

### ISSUE THREAD

**Issue by aje54** [DFE-Digital/architecture#52]
I don't seem to be able to contribute to this repo any more. remote: Permission to DFE-Digital/architecture.git denied to aje54.
fatal: unable to access 'https://github.com/DFE-Digital/architecture.git/': The requested URL returned error: 403. I notice that there is no "edit pencil" on the readme.md too (for me anyway).

**Comment by luke-slowen** [comment]
Have added you to the architecture team - should give you rights?

**Comment by aje54** [comment]
that has worked, thanks. I was surprised to see it locked down TBH?

**Comment by aje54** [comment]
fixed by adding me to the group
